# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=140)),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True)),
                ('deleted', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='outliner.Entry')),
            ],
        ),
    ]
