# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outliner', '0002_auto_20170205_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outliner.Entry'),
        ),
    ]
